config/routes.rb
Rails.application.routes.draw do
  root 'movies#index'
  resources :lists, only: %i[index show new create destroy] do
    resources :bookmarks, only: %i[new create]
    resources :reviews, only: %i[new create]
  end

  get 'movies/list/:list_type', to: 'movies#list', as: 'movies_list'
  get 'movies/:id', to: 'movies#show', as: 'movie'
  get 'tv_series', to: 'tv_series#index'
  get 'tv_series/list/:list_type', to: 'tv_series#list', as: 'tv_series_list'
  get 'tv_series/:id', to: 'tv_series#show', as: 'tv_serie'
  resources :actors, only: %i[index show]

  resources :bookmarks, only: [:destroy]
  resources :reviews, only: [:destroy]
end

app/models/actor.rb
require 'net/http'
require 'json'

class Actor < ApplicationRecord
  validates :tmdb_id, uniqueness: true

  def self.fetch_and_cache_actors(pages = 5)
    api_key = ENV['TMDB_API_KEY']

    (1..pages).each do |page|
      url = URI("https://api.themoviedb.org/3/person/popular?api_key=#{api_key}&page=#{page}")

      http = Net::HTTP.new(url.host, url.port)
      http.use_ssl = true

      request = Net::HTTP::Get.new(url)
      response = http.request(request)
      actors_data = JSON.parse(response.body)['results']

      actors_data.each do |actor_data|
        actor = Actor.find_or_initialize_by(tmdb_id: actor_data['id'])
        actor.update(
          name: actor_data['name'],
          biography: actor_data['biography'],
          birthday: actor_data['birthday'],
          profile_path: actor_data['profile_path'],
          popularity: actor_data['popularity']
        )
      end
    end
  rescue StandardError => e
    Rails.logger.error("Error fetching #{list_type} actors: #{e.message}")
    nil
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates_uniqueness_of :movie, scope: :list
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  has_many :reviews, dependent: :destroy
  has_one_attached :photo

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
require 'net/http'
require 'json'

class Movie < ApplicationRecord
  validates :tmdb_id, uniqueness: true

  def self.fetch_and_cache_movies(list_type, pages = 5)
    api_key = ENV['TMDB_API_KEY']

    (1..pages).each do |page|
      url = URI("https://api.themoviedb.org/3/movie/#{list_type}?api_key=#{api_key}&page=#{page}")

      http = Net::HTTP.new(url.host, url.port)
      http.use_ssl = true

      request = Net::HTTP::Get.new(url)
      response = http.request(request)
      movies_data = JSON.parse(response.body)['results']

      movies_data.each do |movie_data|
        movie = Movie.find_or_initialize_by(tmdb_id: movie_data['id'])
        movie.update(
          title: movie_data['title'],
          overview: movie_data['overview'],
          release_date: movie_data['release_date'],
          poster_path: movie_data['poster_path'],
          vote_average: movie_data['vote_average'],
          list_type:
        )
      end
    end
  rescue StandardError => e
    Rails.logger.error("Error fetching #{list_type} movies: #{e.message}")
    nil
  end
end

app/models/review.rb
class Review < ApplicationRecord
  AUTHORIZED_RATINGS = (1..5)

  before_validation :set_defaults
  belongs_to :list
  validates :content, presence: true
  validates :rating, inclusion: { in: (0..5) }, numericality: { only_integer: true }

  private

  def set_defaults
    self.rating = 0 if rating.blank?
  end
end

app/models/serie.rb
class TvSerie < ApplicationRecord
end

app/models/tv_serie.rb
require 'net/http'
require 'json'

class TvSerie < ApplicationRecord
  validates :tmdb_id, uniqueness: true

  def self.fetch_and_cache_tv_series(list_type, pages = 5)
    api_key = ENV['TMDB_API_KEY']

    (1..pages).each do |page|
      url = URI("https://api.themoviedb.org/3/tv/#{list_type}?api_key=#{api_key}&page=#{page}")

      http = Net::HTTP.new(url.host, url.port)
      http.use_ssl = true

      request = Net::HTTP::Get.new(url)
      response = http.request(request)
      tv_series_data = JSON.parse(response.body)['results']

      tv_series_data.each do |tv_serie_data|
        tv_serie = TvSerie.find_or_initialize_by(tmdb_id: tv_serie_data['id'])
        tv_serie.update(
          name: tv_serie_data['name'],
          overview: tv_serie_data['overview'],
          first_air_date: tv_serie_data['first_air_date'],
          poster_path: tv_serie_data['poster_path'],
          vote_average: tv_serie_data['vote_average'],
          list_type:
        )
      end
    end
  rescue StandardError => e
    Rails.logger.error("Error fetching #{list_type} tv_series: #{e.message}")
    nil
  end
end

app/controllers/actors_controller.rb
class ActorsController < ApplicationController
  def index
    @actors = Actor.all
  end

  def show
    @actor = Actor.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_list, only: %i[new create]

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list), status: :see_other
  end

  private

  def set_list
    @list = List.find(params[:list_id])
  end

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: %i[show destroy]

  def index
    @lists = List.all
  end

  def show
    @review = Review.new
    @ratings = (1..5)
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @list.destroy
    redirect_to root_path, status: :see_other
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies_lists = Movie.all.group_by(&:list_type)
  end

  def list
    @list_type = params[:list_type]
    @movies = Movie.where(list_type: @list_type)
  end

  def show
    @movie = Movie.find(params[:id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @list = List.find(params[:list_id])
    @review = Review.new(review_params)
    @review.list = @list
    if @review.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to list_path(@review.list), status: :see_other
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/controllers/tv_series_controller.rb
class TvSeriesController < ApplicationController
  def index
    @tv_series_lists = TvSerie.all.group_by(&:list_type)
  end

  def list
    @list_type = params[:list_type]
    @tv_series = TvSerie.where(list_type: @list_type)
  end

  def show
    @tv_serie = TvSerie.find(params[:id])
  end
end

app/helpers/actors_helper.rb
module ActorsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/series_helper.rb
module SeriesHelper
end

app/views/actors/index.html.erb
<div class="container">
  <div class="row">
    <div class="flexbox">
      <div class="header">Popular</div>
    </div>
    <div class="cards">
      <% @actors.each do |a| %>
        <%= link_to actor_path(a), class: "text-decoration-none text-dark" do %>
          <div class="card-trip">
            <div class="image-container">
              <%= image_tag a.profile_path ? "https://image.tmdb.org/t/p/w500#{a.profile_path}" : "default_pfp.jpg" %>
            </div>
            <h2 class="text-truncate card-title"><%= a.name %></h2>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/actors/show.html.erb
<h1>Actors#show</h1>
<p>Find me in app/views/actors/show.html.erb</p>

app/views/bookmarks/_form.html.erb
<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.association :movie %>
  <%= f.input :comment %>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/bookmarks/new.html.erb
<div class="container w-50">
  <h1>New Boookmark</h1>
  <%= render "form", bookmark: @bookmark %>
</div>

app/views/lists/_form.html.erb
<%= simple_form_for(@list) do |f| %>
  <%= f.input :name %>
  <%= f.input :photo, as: :file %>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/lists/_rate.html.erb
<i class="fa-solid fa-star p-1"></i>

app/views/lists/_review_form.html.erb
<%= simple_form_for [@list, @review] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating,
              as: :radio_buttons,
              collection: Review::AUTHORIZED_RATINGS,
              label_method: lambda { |rate| render "rate" },
              item_wrapper_class: "d-inline-block"
  %>
  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/lists/index.html.erb
<div class="banner">
  <div class="container">
    <h1>Your Movie Watch-List</h1>
  </div>
</div>
<div class="container w-50">
  <div class="row">
    <div class="flexbox align-items-center">
      <div class="header">My Lists</div>
      <%= link_to 'New List', new_list_path, class: 'btn btn-primary btn-sm' %>
    </div>
    <div class="list-cards">
      <% @lists.each do |l| %>
        <%= link_to list_path(l), class: "text-decoration-none" do %>
          <div class="card-category"
               style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= cl_image_path l.photo.attached? ? l.photo.key : 'list_background_default', crop: :fill %>)">
            <%= l.name %>
            <object>
              <%= link_to list_path(l), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} do %>
                <i class="fa-solid fa-xmark"></i>
              <% end %>
            </object>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/lists/new.html.erb
<div class="container w-50">
  <h1>New List</h1>
  <%= render "form", article: @article %>
</div>

app/views/lists/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= cl_image_path @list.photo.attached? ? @list.photo.key : 'list_background_default', crop: :fill %>)">
  <div class="container">
    <h1><%= @list.name %></h1>
  </div>
</div>
<div class="container">
  <div class="row my-4">
    <div class="d-flex justify-content-end mb-3">
      <%= link_to 'Add Movie', new_list_bookmark_path(@list), class: 'btn btn-primary btn-sm' %>
    </div>
    <div class="bookmark-cards">
      <% @list.bookmarks.each do |b| %>
        <div class="card-trip" type="button" data-bs-toggle="modal" data-bs-target="#exampleModal"  data-controller="bookmark" data-action="click->bookmark#openModal">
          <img src="https://image.tmdb.org/t/p/w500<%= b.movie.poster_path %>" />
          <div class="card-trip-infos">
              <h2 class="text-truncate"><%= b.movie.title %></h2>
            <p><%= b.movie.overview %></p>
            <div class="flexbox pt-1 border-top">
              <div>
                <i class="fa-solid fa-quote-left"></i>
                <%= b.comment %>
              </div>
              <%= link_to bookmark_path(b), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} do %>
                <i class="fa-regular fa-trash-can text-dark"></i>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <div class="mb-3">
    <div class="header">Reviews</div>
  </div>
  <div class="row">
    <div class="col">
      <ul class="list-group list-group-flush">
        <% @list.reviews.each do |r| %>
          <li class="list-group-item">
            <div>
              <% r.rating.times do %>
                <i class="fa-solid fa-star" style="color: gold"></i>
              <% end %>
              <% (5 - r.rating).times do %>
                <i class="fa-solid fa-star"></i>
              <% end %>
            </div>
            <div class="flexbox">
              <%= r.content %>
              <%= link_to review_path(r), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} do %>
                <i class="fa-regular fa-trash-can text-dark ms-2"></i>
              <% end %>
            </div>
          </li>
        <% end %>
      </ul>
    </div>
    <div class="col">
      <%= render "review_form", review: @review %>
    </div>
  </div>
</div>

<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
      </div>
    </div>
  </div>
</div>

app/views/movies/index.html.erb
<div class="container">
  <% @movies_lists.each do |list, movies| %>
    <div class="row mb-4">
      <div class="flexbox">
        <div class="header"><%= list.humanize %></div>
      </div>
      <div class="cards">
        <% movies.each do |m| %>
          <%= link_to movie_path(m), class: "text-decoration-none text-dark" do %>
            <div class="card-trip">
              <div class="image-container">
                <img src="https://image.tmdb.org/t/p/w500<%= m.poster_path %>" />
              </div>
              <h2 class="text-truncate card-title"><%= m.title %></h2>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/movies/list.html.erb
<div class="container">
  <div class="row">
    <div class="flexbox">
      <div class="header"><%= @list_type.humanize %></div>
    </div>
    <div class="cards">
      <% @movies.each do |m| %>
        <div class="card-trip">
          <div class="image-container">
            <img src="https://image.tmdb.org/t/p/w500<%= m.poster_path %>" />
          </div>
          <h2 class="text-truncate card-title"><%= m.title %></h2>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/movies/show.html.erb
<h1>Movies#show</h1>
<p>Find me in app/views/movies/show.html.erb</p>