config/routes.rb
Rails.application.routes.draw do
  root 'movies#index'
  resources :lists, only: %i[index show new create destroy] do
    resources :bookmarks, only: %i[new create]
    resources :reviews, only: %i[new create]
  end

  get 'movies/list/:list_type', to: 'movies#list', as: 'movies_list'
  get 'movies/:id', to: 'movies#show', as: 'movie'
  get 'tv_series', to: 'tv_series#index'
  get 'tv_series/list/:list_type', to: 'tv_series#list', as: 'tv_series_list'
  get 'tv_series/:id', to: 'tv_series#show', as: 'tv_serie'
  resources :actors, only: %i[index show]

  resources :bookmarks, only: [:destroy]
  resources :reviews, only: [:destroy]
end

app/models/actor.rb
require 'net/http'
require 'json'

class Actor < ApplicationRecord
  validates :tmdb_id, uniqueness: true

  def self.fetch_and_cache_actors(pages = 5)
    api_key = ENV['TMDB_API_KEY']

    (1..pages).each do |page|
      url = URI("https://api.themoviedb.org/3/person/popular?api_key=#{api_key}&page=#{page}")

      http = Net::HTTP.new(url.host, url.port)
      http.use_ssl = true

      request = Net::HTTP::Get.new(url)
      response = http.request(request)
      actors_data = JSON.parse(response.body)['results']

      actors_data.each do |actor_data|
        actor = Actor.find_or_initialize_by(tmdb_id: actor_data['id'])
        actor.update(
          name: actor_data['name'],
          biography: actor_data['biography'],
          birthday: actor_data['birthday'],
          profile_path: actor_data['profile_path'],
          popularity: actor_data['popularity']
        )
      end
    end
  rescue StandardError => e
    Rails.logger.error("Error fetching #{list_type} actors: #{e.message}")
    nil
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates_uniqueness_of :movie, scope: :list
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  has_many :reviews, dependent: :destroy
  has_one_attached :photo

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
require 'net/http'
require 'json'

class Movie < ApplicationRecord
  validates :tmdb_id, uniqueness: true

  def self.fetch_and_cache_movies(list_type, pages = 5)
    api_key = ENV['TMDB_API_KEY']

    (1..pages).each do |page|
      url = URI("https://api.themoviedb.org/3/movie/#{list_type}?api_key=#{api_key}&page=#{page}")

      http = Net::HTTP.new(url.host, url.port)
      http.use_ssl = true

      request = Net::HTTP::Get.new(url)
      response = http.request(request)
      movies_data = JSON.parse(response.body)['results']

      movies_data.each do |movie_data|
        movie = Movie.find_or_initialize_by(tmdb_id: movie_data['id'])
        movie.update(
          title: movie_data['title'],
          overview: movie_data['overview'],
          release_date: movie_data['release_date'],
          poster_path: movie_data['poster_path'],
          vote_average: movie_data['vote_average'],
          list_type:
        )
      end
    end
  rescue StandardError => e
    Rails.logger.error("Error fetching #{list_type} movies: #{e.message}")
    nil
  end
end

app/models/review.rb
class Review < ApplicationRecord
  AUTHORIZED_RATINGS = (1..5)

  before_validation :set_defaults
  belongs_to :list
  validates :content, presence: true
  validates :rating, inclusion: { in: (0..5) }, numericality: { only_integer: true }

  private

  def set_defaults
    self.rating = 0 if rating.blank?
  end
end

app/models/serie.rb
class TvSerie < ApplicationRecord
end

app/models/tv_serie.rb
require 'net/http'
require 'json'

class TvSerie < ApplicationRecord
  validates :tmdb_id, uniqueness: true

  def self.fetch_and_cache_tv_series(list_type, pages = 5)
    api_key = ENV['TMDB_API_KEY']

    (1..pages).each do |page|
      url = URI("https://api.themoviedb.org/3/tv/#{list_type}?api_key=#{api_key}&page=#{page}")

      http = Net::HTTP.new(url.host, url.port)
      http.use_ssl = true

      request = Net::HTTP::Get.new(url)
      response = http.request(request)
      tv_series_data = JSON.parse(response.body)['results']

      tv_series_data.each do |tv_serie_data|
        tv_serie = TvSerie.find_or_initialize_by(tmdb_id: tv_serie_data['id'])
        tv_serie.update(
          name: tv_serie_data['name'],
          overview: tv_serie_data['overview'],
          first_air_date: tv_serie_data['first_air_date'],
          poster_path: tv_serie_data['poster_path'],
          vote_average: tv_serie_data['vote_average'],
          list_type:
        )
      end
    end
  rescue StandardError => e
    Rails.logger.error("Error fetching #{list_type} tv_series: #{e.message}")
    nil
  end
end

app/controllers/actors_controller.rb
class ActorsController < ApplicationController
  def index
    @actors = Actor.all
  end

  def show
    @actor = Actor.find(params[:id])
  end
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_list, only: %i[new create]

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list), status: :see_other
  end

  private

  def set_list
    @list = List.find(params[:list_id])
  end

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: %i[show destroy]

  def index
    @lists = List.all
  end

  def show
    @review = Review.new
    @ratings = (1..5)
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @list.destroy
    redirect_to root_path, status: :see_other
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies_lists = Movie.all.group_by(&:list_type)
  end

  def list
    @list_type = params[:list_type]
    @movies = Movie.where(list_type: @list_type)
  end

  def show
    @movie = Movie.find(params[:id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @list = List.find(params[:list_id])
    @review = Review.new(review_params)
    @review.list = @list
    if @review.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to list_path(@review.list), status: :see_other
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/actors_helper.rb
module ActorsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/series_helper.rb
module SeriesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="navbar navbar-expand-sm navbar-lewagon">
      <div class="container-fluid">
        <%= link_to root_path, class: "navbar-brand" do %>
          <%= image_tag "popcorn.jpg" %>
        <% end %>
        <div class="navbar-collapse">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Movies
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "All Movies", root_path, class: "dropdown-item" %></li>
                <li><%= link_to "Now Playing", movies_list_path('now_playing'), class: "dropdown-item" %></li>
                <li><%= link_to "Popular", movies_list_path('popular'), class: "dropdown-item" %></li>
                <li><%= link_to "Top Rated", movies_list_path('top_rated'), class: "dropdown-item" %></li>
                <li><%= link_to "Upcoming", movies_list_path('upcoming'), class: "dropdown-item" %></li>
              </ul>
            </li>
            <li class="dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Series
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "All Series", tv_series_path, class: "dropdown-item" %></li>
                <li><%= link_to "Airing today", tv_series_list_path('airing_today'), class: "dropdown-item" %></li>
                <li><%= link_to "Popular", tv_series_list_path('popular'), class: "dropdown-item" %></li>
                <li><%= link_to "Top Rated", tv_series_list_path('top_rated'), class: "dropdown-item" %></li>
                <li><%= link_to "On the air", tv_series_list_path('on_the_air'), class: "dropdown-item" %></li>
              </ul>
            </li>
            <li>
              <%= link_to "Actors", actors_path, class: "nav-link" %>
            </li>
            <li>
              <%= link_to "My Lists", lists_path, class: "nav-link" %>
            </li>
          </ul>
          <form class="d-flex" role="search">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
          </form>
        </div>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>